version: "2.2"

services:

  # InfluxDB
  db:
    image: influxdb:1.7.6
    container_name: db
    ports:
      - 8086:8086
    volumes:
      - $PWD/db:/var/lib/influxdb

  #Grafana
  monitoring:
    image: grafana/grafana:6.1.6
    container_name: grafana
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - $PWD/grafana:/var/lib/grafana

  # Docker-Android Google emulator Nexus 7.1.1 (Android version: 7.1.1)
  nexus_7.1.1:
    image: budtmo/docker-android-x86-7.1.1:1.8-p1
    container_name: nexus
    privileged: true
    # Increase scale number if needed
    scale: 1
    ports:
      - 4723:4723
      - 6080:6080
    # Change path of apk that you want to test. I use sample_apk that I provide in folder "example"
    volumes:
      - $PWD/src/test/resources/apk:/root/tmp/sample_apk
    environment:
      - DEVICE=Nexus 5
      - CONNECT_TO_GRID=false
      - APPIUM=true
      - AUTO_RECORD=false

  # Docker-Android Google emulator Samsung (Android version: 7.0)
  samsung_7.0:
    image: budtmo/docker-android-x86-7.0:1.8-p1
    container_name: samsung
    privileged: true
    # Increase scale number if needed
    scale: 1
    ports:
      - 6081:6080
      - 4724:4723
    # Change path of apk that you want to test. I use sample_apk that I provide in folder "example"
    volumes:
      - $PWD/src/test/resources/apk:/root/tmp/sample_apk
    environment:
      - DEVICE=Samsung Galaxy S6
      - CONNECT_TO_GRID=false
      - APPIUM=true
      - AUTO_RECORD=false

  # Docker-Android with Genymotion integration
  genymotion:
    image: budtmo/docker-android-genymotion:1.8-p2-beta
    container_name: pixel
    privileged: true
    # Increase scale number if needed
    scale: 1
    ports:
      - 6082:6080
      - 4725:4723
    # Change path of apk that you want to test. I use sample_apk that I provide in folder "example"
    volumes:
      - $PWD/src/test/resources/apk:/root/tmp/sample_apk
      - $PWD/src/test/resources/genymotion:/root/tmp/genymotion
    environment:
      - TYPE=SaaS
      - USER=$USER
      - PASS=$PASS
      - TEMPLATE=/root/tmp/genymotion/devices.json
      - CONNECT_TO_GRID=false
