version: "2.2"

services:

  # InfluxDB
  db:
    image: influxdb:1.7.5
    container_name: db
    ports:
      - 8086:8086
    volumes:
      - $PWD/db:/var/lib/influxdb

  #Grafana
  monitoring:
    image: grafana/grafana:6.1.3
    container_name: grafana
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - $PWD/grafana:/var/lib/grafana

  # Selenium hub
  selenium_hub:
    image: selenium/hub:3.141.59-mercury
    container_name: selenium
    ports:
      - 4444:4444

  # Docker-Android
  nexus_7.1.1:
    image: budtmo/docker-android-x86-7.1.1:1.7-p1
    container_name: docker-android
    privileged: true
    # Increase scale number if needed
    scale: 1
    depends_on:
      - selenium_hub
    ports:
      - 6080:6080
    # Change path of apk that you want to test. I use sample_apk that I provide in folder "example"
    volumes:
      - $PWD/src/test/resources/apk:/root/tmp/sample_apk
    environment:
      - DEVICE=Nexus 5
      - CONNECT_TO_GRID=true
      - APPIUM=true
      - SELENIUM_HOST=selenium_hub
      - AUTO_RECORD=false
